import { withApollo } from '../lib/withApollo';
import { useRouter } from 'next/router';
import { useEffect, useContext } from 'react';
import { useQuery } from '@apollo/react-hooks';
import { useUser } from '@auth0/nextjs-auth0';
import Head from 'next/head';
import HeaderComponent from '../components/organisms/Header/HeaderComponent';
import NavBar from '../components/organisms/NavBar/NavbarComponent';
import HomeTemplateComponent from '../components/templates/HomeTemplateComponent';
import { globalContext } from '../context/globalStore';

function ControlCenter(): React.FC {
  const router = useRouter();

  const { user, error, isLoading } = useUser();

  const { state } = useContext(globalContext);

  useEffect(() => {
    if (!user) return router.push('/');
    // console.log(user);
  }, [router, user]);

  return (
    <div className="flex justify-center align-center w-screen">
      <Head>
        <title>1PS | Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-auto">
        <NavBar />
      </div>
      <div className="flex flex-col flex-auto">
        <HeaderComponent activeContent={state.activeContent} />
        <div className="content-container flex-auto bg-skin-accent-neutral">
          {state.activeContent === 'DASHBOARD' ? (
            <HomeTemplateComponent />
          ) : null}
        </div>
      </div>
    </div>
  );
}

export default ControlCenter;
