import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import { useUser } from '@auth0/nextjs-auth0';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export default function Home(): ReactFC {
  const { user, error, isLoading } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (user) router.push('/controlCenter');
  }, [router, user]);

  return (
    <div className="flex flex-col py-0 px-2 min-h-screen justify-center items-center">
      <Head>
        <title>1PS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col flex-1 justify-center items-center py-2 px-0">
        <h1 className="text-7xl tracking-widest text-skin-inverted">
          WELCOME TO 1PS
        </h1>

        <div className="flex items-center justify-center flex-wrap max-w-screen-md mt-12">
          <a
            href="api/auth/login"
            className="m-4 p-6 text-left text-skin-inverted no-underline border-2 border-base-light border-solid rounded-lg hover:text-skin-accent-light hover:border-skin-accent-light ease-in duration-150"
          >
            <h2 className="mb-4 text-2xl font-semibold">Login &rarr;</h2>
            <p className="m-0 text-xl leading-normal">
              Login to our platform with Auth0
            </p>
          </a>
        </div>
      </main>

      <footer className="text-skin-inverted flex justify-center items-center w-full h-12 border-t border-grey-200 border-solid">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex justify-center items-center flex-grow text-skin-inverted"
        >
          Powered by{' '}
          <span className="h-4 m-2">
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              fill="currentColor"
              className="text-skin-inverted"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
